export const PATH_PUBLIC = {
  home: '/',
  register: '/register',
  login: '/login',
  unauthorized: '/unauthorized',
  notFound: '/404',
};

export const PATH_DASHBOARD = {
  dashboard: '/dashboard',
  usersManagement: '/dashboard/users-management',
  updateRole: '/dashboard/update-role/:userName',
  sendMessage: '/dashboard/send-message',
  inbox: '/dashboard/inbox',
  allMessages: '/dashboard/all-messages',
  systemLogs: '/dashboard/system-logs',
  myLogs: '/dashboard/my-logs',
  Diella: '/dashboard/diella',
  Diellas: '/dashboard/diellas',
  Fatime: '/dashboard/fatime',
  Fatimes: '/dashboard/fatimes',
  Adea: '/dashboard/adea',
  Adeas: '/dashboard/adeas',
  Donjeta: '/dashboard/donjeta',
  Donjetas: '/dashboard/donjetas',
  Product: '/dashboard/product',
  owner: '/dashboard/owner',
  admin: '/dashboard/admin',
  manager: '/dashboard/manager',
  user: '/dashboard/user',
};
